/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekakhir;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class barang extends javax.swing.JFrame {

    DefaultTableModel mod;
    private String SQL;
    private Statement stat;
    
    public barang() {
        
        initComponents();
        bersih();
        kosongkan();
        tampilData();
        setLocationRelativeTo(this);
    }  
    
    private void bersih(){
        textId.setText(null);
        textKode.setText(null);
        textNama.setText(null);
        textNilai.setText(null);
        textKepemilikan.setText(null);
        textAlamat.setText(null);
        
    }
    
    private void kosongkan(){
        textId.setText("");
        textKode.setText("");
        textNama.setText("");
        textNilai.setText("");
        textKepemilikan.setText("");
        textAlamat.setText("");
        textId.requestFocus();
        
    }
    
    private void tampilData(){
        mod = new DefaultTableModel();
        mod.addColumn("ID BARANG");
        mod.addColumn("KODE BARANG");
        mod.addColumn("NAMA BARANG");
        mod.addColumn("NILAI");
        mod.addColumn("KEPEMILIKAN ATAS NAMA");
        mod.addColumn("ALAMAT");
        tableBarang.setModel(mod);
        Connection conn = koneksi.getConnection();
        try{
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from barang";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while(res.next()){
                mod.addRow(new Object[]{
                   res.getString("id_barang"),
                   res.getString("kode_barang"),
                   res.getString("nama_barang"),
                   res.getString("nilai"),
                   res.getString("kepemilikan"),
                   res.getString("alamat"),
                });
            }
        }catch (SQLException e){
            System.out.println(e);
            
        }
            
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        textKode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        textNilai = new javax.swing.JTextField();
        textKepemilikan = new javax.swing.JTextField();
        textAlamat = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("ID BARANG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 24, -1, -1));

        jLabel2.setBackground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("KODE BARANG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 64, -1, -1));

        textId.setBackground(new java.awt.Color(51, 255, 255));
        textId.setText("jTextField1");
        getContentPane().add(textId, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 21, 231, -1));

        textKode.setBackground(new java.awt.Color(51, 255, 255));
        textKode.setText("jTextField2");
        getContentPane().add(textKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 61, 231, -1));

        jLabel3.setBackground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("NAMA BARANG");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 99, -1, -1));

        jLabel4.setBackground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("NILAI BARANG");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 139, -1, -1));

        jLabel5.setBackground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("KEPIMILIKAN ATAS NAMA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 179, -1, -1));

        jLabel6.setBackground(new java.awt.Color(51, 255, 255));
        jLabel6.setText("ALAMAT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 219, -1, -1));

        textNama.setBackground(new java.awt.Color(51, 255, 255));
        textNama.setText("jTextField3");
        getContentPane().add(textNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 96, 231, -1));

        textNilai.setBackground(new java.awt.Color(51, 255, 255));
        textNilai.setText("jTextField4");
        getContentPane().add(textNilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 136, 231, -1));

        textKepemilikan.setBackground(new java.awt.Color(51, 255, 255));
        textKepemilikan.setText("jTextField5");
        getContentPane().add(textKepemilikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 176, 231, -1));

        textAlamat.setBackground(new java.awt.Color(51, 255, 255));
        textAlamat.setText("jTextField6");
        getContentPane().add(textAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 216, 231, -1));

        btnSave.setBackground(new java.awt.Color(51, 255, 255));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 268, -1, -1));

        btnAdd.setBackground(new java.awt.Color(51, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 268, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(51, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 268, -1, -1));

        btnDelete.setBackground(new java.awt.Color(51, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 268, -1, -1));

        btnPrint.setBackground(new java.awt.Color(51, 255, 255));
        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 268, -1, -1));

        btnExit.setBackground(new java.awt.Color(51, 255, 255));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 268, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(51, 255, 255));

        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 706, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
        ("insert into barang (id_barang, kode_barang, nama_barang, nilai, kepemilikan, alamat) value (?,?,?,?,?,?)");
            stmt.setString(1, textId.getText());
            stmt.setString(2, textKode.getText());
            stmt.setString(3, textNama.getText());
            stmt.setString(4, textNilai.getText());
            stmt.setString(5, textKepemilikan.getText());
            stmt.setString(6, textAlamat.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         try{
          String sql="INSERT INTO barang VALUES ('"+textId.getText()+"','"+textKode.getText()+"','"+textNama.getText()+"','"+textNilai.getText()+"','"+textKepemilikan.getText()+"','"+textAlamat.getText()+"')";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(null, "Tambah Data Telah Berhasil");
          }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        bersih();
        tampilData();                                   
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
          String sql="UPDATE  barang SET kode_barang = '"+textKode.getText()+"',nama_barang = '"+textNama.getText()+"',nilai = '"+textNilai.getText()+"',kepemilikan = '"+textKepemilikan.getText()+"',alamat = '"+textAlamat.getText()+"'";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(null, "Data Telah Berhasil Diupdate");
          }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Edit Gagal"+e.getMessage());
        }
        tampilData();
        kosongkan();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMouseClicked
        // TODO add your handling code here:
         int i = tableBarang.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)tableBarang.getValueAt(i, 0);
        String code1 = (String)tableBarang.getValueAt(i, 1);
        String code2 = (String)tableBarang.getValueAt(i, 2);
        String code3 = (String)tableBarang.getValueAt(i, 3);
        String code4 = (String)tableBarang.getValueAt(i, 4);
        String code5 = (String)tableBarang.getValueAt(i, 5);
        textId.setText(code);
        textKode.setText(code1);
        textNama.setText(code2);
        textNilai.setText(code3);
        textKepemilikan.setText(code4);
        textAlamat.setText(code5);
    }//GEN-LAST:event_tableBarangMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try{
          String sql="delete from barang where id_barang='"+textId.getText()+"'";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(this, "Telah Berhasil dihapus");
          
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        bersih();
        tampilData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/projekAkhir/laporanData.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBarang;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textKepemilikan;
    private javax.swing.JTextField textKode;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNilai;
    // End of variables declaration//GEN-END:variables
}
