/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekakhir;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class kondisi extends javax.swing.JFrame {

    DefaultTableModel mod;
    private String SQL;
    private Statement stat;
    
    public kondisi() {
        initComponents();
        bersih();
        kosongkan();
        tampilData();
        setLocationRelativeTo(this);
    }
    
    private void bersih(){
        textKode.setText(null);
        textNama.setText(null);
        textKondisi.setText(null);
        textJumlah.setText(null);
        
    }
    
    private void kosongkan(){
        textKode.setText("");
        textNama.setText("");
        textKondisi.setText("");
        textJumlah.setText("");
        textKode.requestFocus();
        
    }
    
    private void tampilData(){
        mod = new DefaultTableModel();
        mod.addColumn("KODE BARANG");
        mod.addColumn("NAMA BARANG");
        mod.addColumn("KONDISI BARANG");
        mod.addColumn("JUMLAH BARANG");
        tableKondisi.setModel(mod);
        Connection conn = koneksi.getConnection();
        try{
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from kondisi";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while(res.next()){
                mod.addRow(new Object[]{
                   res.getString("kode_barang"),
                   res.getString("nama_barang"),
                   res.getString("kondisi"),
                   res.getString("jumlah"),
                });
            }
        }catch (SQLException e){
            System.out.println(e);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textKondisi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKondisi = new javax.swing.JTable();
        textJumlah = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textKode = new javax.swing.JTextField();
        textNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textKondisi.setBackground(new java.awt.Color(0, 255, 255));
        textKondisi.setText("jTextField3");
        getContentPane().add(textKondisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 96, 220, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 255, 255));

        tableKondisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKondisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKondisiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKondisi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 239, 596, 130));

        textJumlah.setBackground(new java.awt.Color(0, 255, 255));
        textJumlah.setText("jTextField4");
        getContentPane().add(textJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 136, 220, -1));

        btnSave.setBackground(new java.awt.Color(0, 255, 255));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 184, -1, -1));

        btnAdd.setBackground(new java.awt.Color(0, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 184, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 184, -1, -1));

        btnDelete.setBackground(new java.awt.Color(0, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 184, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("KODE BARANG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 24, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("NAMA BARANG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 64, -1, -1));

        textKode.setBackground(new java.awt.Color(0, 255, 255));
        textKode.setText("jTextField1");
        getContentPane().add(textKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 21, 220, -1));

        textNama.setBackground(new java.awt.Color(0, 255, 255));
        textNama.setText("jTextField2");
        getContentPane().add(textNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 61, 220, -1));

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("KONDISI BARANG");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 99, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("JUMLAH BARANG");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 139, -1, -1));

        btnPrint.setBackground(new java.awt.Color(0, 255, 255));
        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 184, -1, -1));

        btnExit.setBackground(new java.awt.Color(0, 255, 255));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 184, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
        ("insert into kondisi (kode_barang, nama_barang, kondisi, jumlah) value (?,?,?,?)");
            stmt.setString(1, textKode.getText());
            stmt.setString(2, textNama.getText());
            stmt.setString(3, textKondisi.getText());
            stmt.setString(4, textJumlah.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Telah Berhasil Disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try{
          String sql="INSERT INTO kondisi VALUES ('"+textKode.getText()+"','"+textNama.getText()+"','"+textKondisi.getText()+"','"+textJumlah.getText()+"')";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(null, "Tambah Data Telah Berhasil");
          }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        bersih();
        tampilData();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
          String sql="UPDATE  kondisi SET nama_barang = '"+textNama.getText()+"',kondisi = '"+textKondisi.getText()+"',jumlah = '"+textJumlah.getText()+"'";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(null, "Data Telah Berhasil Diupdate");
          }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Edit Gagal"+e.getMessage());
        }
        tampilData();
        kosongkan();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tableKondisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKondisiMouseClicked
        // TODO add your handling code here:
        int i = tableKondisi.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)tableKondisi.getValueAt(i, 0);
        String code1 = (String)tableKondisi.getValueAt(i, 1);
        String code2 = (String)tableKondisi.getValueAt(i, 2);
        String code3 = (String)tableKondisi.getValueAt(i, 3);
        textKode.setText(code);
        textNama.setText(code1);
        textKondisi.setText(code2);
        textJumlah.setText(code3);
    }//GEN-LAST:event_tableKondisiMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try{
          String sql="delete from kondisi where kode_barang='"+textKode.getText()+"'";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(this, "Data Telah Berhasil dihapus");
          
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        bersih();
        tampilData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/projekAkhir/laporan_Kondisi.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kondisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kondisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kondisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kondisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kondisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKondisi;
    private javax.swing.JTextField textJumlah;
    private javax.swing.JTextField textKode;
    private javax.swing.JTextField textKondisi;
    private javax.swing.JTextField textNama;
    // End of variables declaration//GEN-END:variables
}
