/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekakhir;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class pegawai extends javax.swing.JFrame {

    DefaultTableModel mod;
    private String SQL;
    private Statement stat;
    
    public pegawai() {
        initComponents();
        bersih();
        kosongkan();
        tampilData();
        setLocationRelativeTo(this);
    }
    
    private void bersih(){
        textNip.setText(null);
        textNama.setText(null);
        textJenis.setText(null);
        textTlahir.setText(null);
        textJabatan.setText(null);
        textAlamat.setText(null);
        
    }
    
    private void kosongkan(){
        textNip.setText("");
        textNama.setText("");
        textJenis.setText("");
        textTlahir.setText("");
        textJabatan.setText("");
        textAlamat.setText("");
        textNip.requestFocus();
        
    }
    
    private void tampilData(){
        mod = new DefaultTableModel();
        mod.addColumn("NIP");
        mod.addColumn("NAMA PEGAWAI");
        mod.addColumn("JENIS KELAMIN");
        mod.addColumn("TANGGAL LAHIR");
        mod.addColumn("JABATAN");
        mod.addColumn("ALAMAT");
        tablePegawai.setModel(mod);
        Connection conn = koneksi.getConnection();
        try{
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from pegawai";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while(res.next()){
                mod.addRow(new Object[]{
                   res.getString("nip"),
                   res.getString("nama_pegawai"),
                   res.getString("jenis_kelamin"),
                   res.getString("tanggal_lahir"),
                   res.getString("jabatan"),
                   res.getString("alamat"),
                });
            }
        }catch (SQLException e){
            System.out.println(e);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        textJenis = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePegawai = new javax.swing.JTable();
        textTlahir = new javax.swing.JTextField();
        textJabatan = new javax.swing.JTextField();
        textAlamat = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNip = new javax.swing.JTextField();
        textNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("ALAMAT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 219, -1, -1));

        textJenis.setBackground(new java.awt.Color(0, 255, 255));
        textJenis.setText("jTextField3");
        getContentPane().add(textJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 96, 210, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 255, 255));

        tablePegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tablePegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePegawai);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 311, 678, 106));

        textTlahir.setBackground(new java.awt.Color(0, 255, 255));
        textTlahir.setText("jTextField4");
        getContentPane().add(textTlahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 136, 210, -1));

        textJabatan.setBackground(new java.awt.Color(0, 255, 255));
        textJabatan.setText("jTextField5");
        getContentPane().add(textJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 176, 210, -1));

        textAlamat.setBackground(new java.awt.Color(0, 255, 255));
        textAlamat.setText("jTextField6");
        getContentPane().add(textAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 216, 210, -1));

        btnSave.setBackground(new java.awt.Color(0, 255, 255));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 268, -1, -1));

        btnAdd.setBackground(new java.awt.Color(0, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 268, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 268, -1, -1));

        btnDelete.setBackground(new java.awt.Color(0, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 268, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("NIP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 24, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("NAMA PEGAWAI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 64, -1, -1));

        textNip.setBackground(new java.awt.Color(0, 255, 255));
        textNip.setText("jTextField1");
        getContentPane().add(textNip, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 21, 210, -1));

        textNama.setBackground(new java.awt.Color(0, 255, 255));
        textNama.setText("jTextField2");
        getContentPane().add(textNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 61, 210, -1));

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("JENIS KELAMIN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 99, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("TANGGAL LAHIR");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 139, -1, -1));

        btnPrint.setBackground(new java.awt.Color(0, 255, 255));
        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 268, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("JABATAN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 179, -1, -1));

        btnExit.setBackground(new java.awt.Color(0, 255, 255));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 268, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
        ("insert into pegawai (nip, nama_pegawai, jenis_kelamin, tanggal_lahir, jabatan, alamat) value (?,?,?,?,?,?)");
            stmt.setString(1, textNip.getText());
            stmt.setString(2, textNama.getText());
            stmt.setString(3, textJenis.getText());
            stmt.setString(4, textTlahir.getText());
            stmt.setString(5, textJabatan.getText());
            stmt.setString(6, textAlamat.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Telah Berhasil Disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try{
          String sql="INSERT INTO pegawai VALUES ('"+textNip.getText()+"','"+textNama.getText()+"','"+textJenis.getText()+"','"+textTlahir.getText()+"','"+textJabatan.getText()+"','"+textAlamat.getText()+"')";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(null, "Tambah Data Telah Berhasil");
          }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        bersih();
        tampilData();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
          String sql="UPDATE  pegawai SET nama_pegawai = '"+textNama.getText()+"',Jenis_Kelamin = '"+textJenis.getText()+"',tanggal_lahir = '"+textTlahir.getText()+"',jabatan = '"+textJabatan.getText()+"',alamat = '"+textAlamat.getText()+"'";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(null, "Data Telah Berhasil Diupdate");
          }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Edit Gagal"+e.getMessage());
        }
        tampilData();
        kosongkan();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tablePegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePegawaiMouseClicked
        // TODO add your handling code here:
        int i = tablePegawai.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)tablePegawai.getValueAt(i, 0);
        String code1 = (String)tablePegawai.getValueAt(i, 1);
        String code2 = (String)tablePegawai.getValueAt(i, 2);
        String code3 = (String)tablePegawai.getValueAt(i, 3);
        String code4 = (String)tablePegawai.getValueAt(i, 4);
        String code5 = (String)tablePegawai.getValueAt(i, 5);
        textNip.setText(code);
        textNama.setText(code1);
        textJenis.setText(code2);
        textTlahir.setText(code3);
        textJabatan.setText(code4);
        textAlamat.setText(code5);
    }//GEN-LAST:event_tablePegawaiMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try{
          String sql="delete from pegawai where nip='"+textNip.getText()+"'";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(this, "Data Telah Berhasil dihapus");
          
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        bersih();
        tampilData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/projekAkhir/laporanPegawai.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePegawai;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textJabatan;
    private javax.swing.JTextField textJenis;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNip;
    private javax.swing.JTextField textTlahir;
    // End of variables declaration//GEN-END:variables
}
